language: python
python:
    - "2.7"

cache:
  directories:
  - $HOME/virtualenv/python2.7.9
  - $HOME/.cache/pip

sudo: false

compiler:
    - gcc

before_install:
    # gaia has been cloned to Kitware/gaia by travis
    # girder needs to be cloned and then gaia moved under girder
    - cd $HOME/build
    # remove existing girder dir, it remains from caching operations
    - rm -rf girder
    # Gaia won't work with v1.4.1 of girder, set to revision 54d37d4
    - git clone https://github.com/girder/girder.git

    - mv OpenGeoscience/gaia girder/plugins
    - cp girder/plugins/gaia/server/conf/gaia.dist.cfg girder/plugins/gaia/server/conf/gaia.local.cfg

    - cd girder
    - git checkout 54d37d4

    # Show the memory state; this lets us more quickly determine when the
    # travis environment is bad
    - vmstat
    - export IGNORE_PLUGINS=celery_jobs,geospatial,google_analytics,hdfs_assetstore,jquery_widgets,metadata_extractor,mongo_search,oauth,provenance,thumbnails,user_quota,vega;
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then export PY3="true"; else export PY2="true"; fi
    - if [ -n "${PY3}" ]; then export MONGO_VERSION=3.0.2; export PY_COVG="OFF"; else export MONGO_VERSION=2.6.9; export PY_COVG="ON"; export DEPLOY=true; fi

    # mongo
    - pushd "${HOME}"
    - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGO_VERSION}.tgz" | gunzip -c | tar x
    - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    # cmake
    - cd $HOME
    - curl -L "http://cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - cmake --version

install:
    - cd $HOME/build/girder
    - scripts/InstallPythonRequirements.py --mode=dev --ignore-plugins=${IGNORE_PLUGINS}
    - cd /home/travis/build/girder
    # build and install girder
    - npm install

script:
    - mkdir _build
    - cd _build
    - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} ..
    - JASMINE_TIMEOUT=15000 ctest -R gaia -VV