language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "2.6"

before_install:
  - pushd "${HOME}"
  - curl "http://www.cmake.org/files/v3.2/cmake-3.2.0-rc2-Linux-x86_64.tar.gz" | gunzip -c | tar x
  - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - cmake --version
  - export CMAKE_PYTHON_VERSION=$(python -c 'import sys; print("{0}.{1}".format(sys.version_info.major, sys.version_info.minor))')
  - env
  - if [ -z "${CMAKE_PYTHON_VERSION}" ] ; then export CMAKE_PYTHON_VERSION="2.6" ; pip install importlib ; fi

install:
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install geopandas==0.1.1

script:
  - rm -fr _build || true
  - mkdir _build
  - pushd _build
  - cmake ..
  - ctest -VV -S ../cmake/travis_continuous.cmake || true
  - pushd ../tests/cases
  - if [ "${CMAKE_PYTHON_VERSION}" != "2.6" ] ; then coveralls ; fi
  - popd
  - if [ -f test_failed ] ; then false ; fi
  - popd
