language: python

sudo: required
dist: trusty

addons:
  postgresql: "9.4"
  apt:
    packages:
      - python-dev
      - libgdal1-dev
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev
      - gfortran

services:
  - postgresql

python:
  - "2.7"
  - "3.4"

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - sudo apt-get -qq update

install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .


script:
  - python -m unittest discover
  - flake8 --config tests/flake8.cfg gaia tests
