language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "2.6"

before_install:
  - pushd "${HOME}"
  - curl "http://www.cmake.org/files/v3.2/cmake-3.2.0-rc2-Linux-x86_64.tar.gz" | gunzip -c | tar x
  - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - cmake --version
  - env

install:
  - sudo apt-get update
  - sudo apt-get install -y libgdal-dev
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - rm -fr _build || true
  - mkdir _build
  - pushd _build
  - cmake ..
  - ctest -VV -S ../cmake/travis_continuous.cmake || true
  - if [ -f test_failed ] ; then false ; fi
  - popd
  - python setup.py develop
  - rm -fr tmp; mkdir tmp
  - pushd tmp
  - python -c "import gaia; print(gaia.__version__)"
  - popd

after_success:
  - if [ "${TRAVIS_PYTHON_VERSION}" != "2.6" ] ; then coveralls ; fi
