language: python

sudo: false

addons:
  apt:
    packages:
      - python-dev
      - libgdal1-dev

python:
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - pushd "${HOME}"
  - curl -L "http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz" | gunzip -c | tar x
  - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - cmake --version
  - env

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - python -m unittest discover
  - rm -fr tmp; mkdir tmp
  - pushd tmp
  - python -c "import gaia; print(gaia.__version__)"
  - popd

after_success:
  - if [ "${TRAVIS_PYTHON_VERSION}" != "2.6" ] ; then cd tests/cases; coveralls ; fi
