language: python

sudo: required
dist: trusty

addons:
  postgresql: "9.3"
  apt:
    packages:
      - python-dev
      - libgdal1-dev

services:
  - postgresql

python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get -qq update

install:
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .


script:
  - python -m unittest discover
  - flake8 --config tests/flake8.cfg gaia tests
