# conda_env.yml
# Configuration file for creating a Conda Environment with dependencies needed for Gaia.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create -f conda_env.yml

name: gaia

channels:
- conda-forge
- defaults

dependencies:
- numpy==1.10.4
- six==1.10.0
- requests==2.9.2
- shapely==1.5.13
- geopandas==0.1.1
- pillow==3.2.0
- gdal==1.11.4
- celery==3.1.23
- psycopg2==2.6.2
- geoalchemy2==0.3.0